---
abstract: 'manage collections of SAX processors'
author:
  - 'Barry Slaymaker'
  - 'Chris Prather <chris@prather.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test: 0
  Test::More: 0
  XML::SAX::PurePerl: 0
  XML::SAX::Writer: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-SAX-Machines
requires:
  Carp: 0
  Data::Dumper: 0
  Exporter: 0
  File::Spec: 0
  File::Spec::Unix: 0
  IO::Handle: 0
  Symbol: 0
  UNIVERSAL: 0
  XML::SAX::Base: 0
  XML::SAX::ParserFactory: 0
  XML::SAX::Writer: 0
  base: 0
  constant: 0
  fields: 0
  strict: 0
  vars: 0
resources:
  homepage: https://github.com/perigrin/xml-sax-machines
  repository: https://github.com/perigrin/xml-sax-machines.git
version: 0.43
