---
abstract: ~
author:
  - 'Barrie Slaymaker'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.87'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-SAX-Machines
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  XML::SAX: 0.05
  XML::SAX::Base: 1.02
  XML::SAX::Writer: 0.42
  perl: 5.6.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.42
